name: attendly
description: Aplikasi Presensi Mahasiswa
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  geolocator: ^10.0.0
  geocoding: ^2.1.1
  provider: ^6.1.1
  flutter_otp_text_field: ^1.1.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.1
  intl: ^0.18.1
  flutter_local_notifications: ^17.0.0
  crypto: ^3.0.3
  http: ^1.1.0
  flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
      - .env
  uses-material-design: true